### ISSUE TITLE
Add tests for selenium engines

### ISSUE THREAD

**Issue by wdm0006** [anidata/rasp#3] opened 2017-02-27 23:14 UTC
There is currently a single very simple test for the DefaultEngine, which just verifies that we can get back a non-None response from google.com, this basic testing should be replicated out to the other engines, in this case the selenium based ones.

**Comment by hank-bond** [comment] 2017-03-09 16:47
Should we bother writing tests if they are functional in nature?  I assume we would still have to rewrite them later into mocked unit tests after #12 is completed.

**Comment by wdm0006** [comment] 2017-03-09 17:59
Yeah I think it'd be better to wait on #12

**Comment by hank-bond** [comment] 2017-03-12 19:35
Can we mock the selenium engine?  Is [this pytest extension](http://stackoverflow.com/a/29073954) worth looking into?

**Comment by wdm0006** [comment] 2017-03-13 12:50
That's interesting, not sure if it would work on travis or not.

**Comment by hank-bond** [comment] 2017-03-20 18:21
Revisiting this, are there any practical solutions for unit testing code that employs `selenium`?  I am unable to find any options I would consider viable, which isn't particularly surprising given that `selenium` itself was designed to be employed inside unit tests.

Should we consider this a wash?  It's not even like we have a significant amount of added functionality to test.  The `SeleniumEngine` is mostly just a limited API wrapper on top of the `WebDriver` class, of which is probably thoroughly tested.

**Comment by wdm0006** [comment] 2017-03-20 23:59
I don't know of anything.  I think for now it's fine to lean on the `selenium` project's own internal testing, and try to keep our wrapper around it pretty minimal.

**Comment by hank-bond** [comment] 2017-03-21 22:46
Closing issue since it doesn't seem a prudent use of time to try to work out some monkeypatch/mock method to test this class.

**Closed as completed by hank-bond** 2017-03-21 22:46 UTC
Labels: lang:python, skill:qa, status:assigned
